name: Generate release and publish

on:
  pull_request_target:
    types:
      - closed
run-name: Release and Publish from PR
env:
  FIGMA_PERSONAL_ACCESS_TOKEN: ${{ secrets.FIGMA_TOKEN }}
jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Generate release and publish
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Get Package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ steps.package-version.outputs.current-version}}"
          tag_exists_error: false
          message: "Update version to v${{ steps.package-version.outputs.current-version}}"

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-npm-cache

      - name: Install packages
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm i

      - name: Generate tokens
        run: |
          npm run package:process-tokens
          npm run package:style-dictionary

      - name: Generate icons
        run: |
          npm run package:minify-all-svgs

      - name: Generate Aperta Tokens zip
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a aperta-tokens.zip ./dist/*

      - name: Create the new release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'aperta-tokens.zip'
          tag: "v${{ steps.package-version.outputs.current-version}}"

      - name: Copy package.json
        uses: canastro/copy-file-action@master
        with:
          source: "./package.json"
          target: "./dist/package.json"

      - name: Generate .npmrc
        run: |
          echo @opositatest:registry=https://npm.pkg.github.com > dist/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${GH_OAUTH_TOKEN}' >> dist/.npmrc

      - name: Publish package
        run: npm publish
        working-directory: ./dist
        env:
          GH_OAUTH_TOKEN: ${{secrets.GH_OAUTH_TOKEN}}
